package eu.europa.ec.fisheries.wsdl.user.module;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2020-10-24T19:29:57.246+03:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "UserModuleService", 
                  wsdlLocation = "file:/C:/workspaces/VBoxShared/DGMARE/UVMS-User-APP/model/src/main/resources/contract/UserModuleService.wsdl",
                  targetNamespace = "module.user.wsdl.fisheries.ec.europa.eu") 
public class UserModuleService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("module.user.wsdl.fisheries.ec.europa.eu", "UserModuleService");
    public final static QName UserModulePortType = new QName("module.user.wsdl.fisheries.ec.europa.eu", "UserModulePortType");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspaces/VBoxShared/DGMARE/UVMS-User-APP/model/src/main/resources/contract/UserModuleService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserModuleService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspaces/VBoxShared/DGMARE/UVMS-User-APP/model/src/main/resources/contract/UserModuleService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserModuleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserModuleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserModuleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserModuleService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserModuleService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserModuleService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UserModulePortType
     */
    @WebEndpoint(name = "UserModulePortType")
    public UserModulePortType getUserModulePortType() {
        return super.getPort(UserModulePortType, UserModulePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserModulePortType
     */
    @WebEndpoint(name = "UserModulePortType")
    public UserModulePortType getUserModulePortType(WebServiceFeature... features) {
        return super.getPort(UserModulePortType, UserModulePortType.class, features);
    }

}
